"""Offline API adapter and stub generation utilities."""
from __future__ import annotations
from dataclasses import dataclass

@dataclass
class GeneratedClass:
    name: str
    source: str
    reason: str

class StubGenerator:
    marker = "// Generated by PATCHER offline compatibility layer"
    def generate_class_stub(self, internal_name: str, reason: str) -> GeneratedClass:
        package, _, simple = internal_name.replace("/", ".").rpartition(".")
        lines = [self.marker]
        if package:
            lines.append(f"package {package};")
        lines.append(f"public final class {simple or internal_name} {{")
        lines.append("  private " + (simple or internal_name) + "() { }")
        lines.append("}")
        return GeneratedClass(internal_name, "\n".join(lines), reason)
